// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import FormSection from './FormSection';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	ContactForm,
	FormSection,
	Image,
	Quote,
	Text,
};

export const components = {
	contact_form: ContactForm,
	form_section: FormSection,
	image: Image,
	quote: Quote,
	text: Text,
};
